import { Router } from "express";
import path from "path";
import fs from "fs";
import { getCurrentUser } from "../lib/current-user.js";
import { getMachineApiKey, getOmtpConfig } from "./factory-config.js";
import { PUSHER_B64_CHUNKS } from "../lib/embedded-pusher.js";

const router = Router();
// pnpm always runs scripts from the package directory, so process.cwd()
// is artifacts/api-server in both dev (tsx) and production (CJS bundle).
// Two levels up lands at the workspace root where scripts/ lives.
const SCRIPTS_DIR = path.resolve(process.cwd(), "../../scripts");

/* ── helpers ── */
function getServerUrl(req: any): string {
  const proto = (req.headers["x-forwarded-proto"] as string)?.split(",")[0]?.trim() || "https";
  const host = (req.headers["x-forwarded-host"] as string) || (req.headers["host"] as string) || "localhost";
  return `${proto}://${host}`;
}

/* ── Static guide (public, no auth) ── */
router.get("/omtp-guide", async (_req, res) => {
  const filePath = path.join(SCRIPTS_DIR, "OMTP_Guide.html");
  if (!fs.existsSync(filePath)) return res.status(404).send("Not found");
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.send(fs.readFileSync(filePath, "utf-8"));
});

/* ── Python pusher (public — BAT downloads it automatically) ── */
router.get("/omtp-pusher", async (_req, res) => {
  // Serve the embedded script (compile-time constant, always available in prod)
  const pyBytes = Buffer.from(PUSHER_B64_CHUNKS.join(""), "base64");
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", 'attachment; filename="omtp_log_pusher.py"');
  res.send(pyBytes);
});

/* ══════════════════════════════════════════════════════════════════
   GET /api/downloads/omtp-ready  (Admin only)
   Generates cmms_Start.bat — a fully pre-configured BAT file that:
     - Has SERVER URL and API KEY baked in (no editing needed)
     - Auto-detects production line from OMTP folder name (TAM30202=Line2)
     - Downloads omtp_pusher.py from CMMS automatically
     - Installs Python automatically if missing (silent download)
     - Offers to add itself to Windows Startup (runs hidden/background)
     - Logs output to omtp_log.txt when running as background service
     - Requires ZERO configuration — no questions asked
   ══════════════════════════════════════════════════════════════════ */
router.get("/omtp-ready", async (req, res) => {
  const user = await getCurrentUser(req);
  if (!user || user.role !== "admin") return res.status(403).json({ error: "Admin only" });

  const apiKey = await getMachineApiKey();
  if (!apiKey) return res.status(500).json({ error: "No API key found. Reload Factory Settings." });

  const omtp = await getOmtpConfig();

  // Extract log root from path template — everything before \{MODEL}
  const DEFAULT_PATH = "D:\\OMTP_LOG\\{MODEL}\\data\\{DATE}.csv";
  const pathTemplate = omtp.pathTemplate || DEFAULT_PATH;
  const logRoot = pathTemplate.split(/[\\/]\{MODEL\}/i)[0] || "D:\\OMTP_LOG";

  // Build --column-map arg if admin has configured custom columns
  // NOTE: no trailing ^ here — the ^ goes on the PREVIOUS line (--interval 30 ^)
  const columnMapArg = omtp.columns
    ? `  --column-map "${JSON.stringify(omtp.columns).replace(/"/g, '\\"')}"`
    : "";

  const serverUrl = getServerUrl(req);
  const pusherUrl = `${serverUrl}/api/downloads/omtp-pusher`;

  // Use compile-time embedded chunks — always available regardless of deployment
  // file system layout. Generated by: node scripts/embed-pusher.js
  const b64Chunks = PUSHER_B64_CHUNKS;

  const CRLF = "\r\n";

  /* ─────────────────────────────────────────────────────────────────
     The VBScript launcher (Base64-encoded so the BAT can write it
     safely without quote-escaping issues).
     Window style 0 = completely hidden; False = don't wait (fire and forget).
     The shortcut's WorkingDirectory is set to the BAT folder so that
     "cmms_Start.bat" resolves correctly without a full path here.
  ───────────────────────────────────────────────────────────────── */
  const vbsContent = [
    `Set WshShell = CreateObject("WScript.Shell")`,
    `WshShell.Run "cmms_Start.bat", 0, False`,
  ].join("\r\n");
  const vbsBase64 = Buffer.from(vbsContent, "utf-8").toString("base64");

  const bat = [
    "@echo off",
    "chcp 65001 > nul",
    "title Midea CMMS - OMTP Log Pusher",
    "color 0A",
    "",
    "REM ── Paths ────────────────────────────────────────────────────",
    "set DIR=%~dp0",
    "set PUSHER=%DIR%omtp_log_pusher.py",
    "set VBS=%DIR%cmms_Startup.vbs",
    "set STARTUP=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup",
    "set LNK=%STARTUP%\\cmms_Start.lnk",
    "",
    "echo ============================================================",
    "echo   Midea CMMS - OMTP Log Pusher  [v4 - QR Token Mode]",
    "echo ============================================================",
    "echo.",
    `echo   Server : ${serverUrl}`,
    "echo.",
    "",
    "REM ── Check Python (auto-install if missing) ──────────────────",
    "python --version > nul 2>&1",
    "if %ERRORLEVEL% EQU 0 goto :python_ok",
    "",
    "REM -- Python not in PATH -- check common user install locations --",
    "set PY_FOUND=",
    "for %%V in (313 312 311 310 39 38) do (",
    "    if exist \"%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\python.exe\" (",
    "        set \"PATH=%LOCALAPPDATA%\\Programs\\Python\\Python%%V;%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\Scripts;%PATH%\"",
    "        set PY_FOUND=1",
    "    )",
    "    if exist \"%APPDATA%\\Python\\Python%%V\\python.exe\" (",
    "        set \"PATH=%APPDATA%\\Python\\Python%%V;%APPDATA%\\Python\\Python%%V\\Scripts;%PATH%\"",
    "        set PY_FOUND=1",
    "    )",
    ")",
    "python --version > nul 2>&1",
    "if %ERRORLEVEL% EQU 0 goto :python_ok",
    "",
    "REM -- Still not found -- download and install Python silently ---",
    "echo.",
    "echo   ============================================================",
    "echo   Python not found. Downloading and installing automatically.",
    "echo   This happens once only — please wait 1-2 minutes.",
    "echo   ============================================================",
    "echo.",
    "set PY_INSTALLER=%TEMP%\\python-3.11.9-setup.exe",
    "set PY_URL=https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe",
    "echo   Downloading Python 3.11 installer...",
    "powershell -Command \"Invoke-WebRequest -Uri '%PY_URL%' -OutFile '%PY_INSTALLER%' -UseBasicParsing\" 2>nul",
    "if not exist \"%PY_INSTALLER%\" (",
    "    color 0C",
    "    echo.",
    "    echo   [ERROR] Could not download Python. Check internet connection.",
    "    echo   Try downloading manually: https://www.python.org/downloads/",
    "    echo.",
    "    pause",
    "    exit /b 1",
    ")",
    "echo   Installing Python (no window will appear — please wait)...",
    "\"%PY_INSTALLER%\" /quiet InstallAllUsers=0 PrependPath=1 Include_test=0 Include_launcher=0",
    "del \"%PY_INSTALLER%\" > nul 2>&1",
    "",
    "REM -- Add freshly installed Python to current session PATH ------",
    "for %%V in (313 312 311 310) do (",
    "    if exist \"%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\python.exe\" (",
    "        set \"PATH=%LOCALAPPDATA%\\Programs\\Python\\Python%%V;%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\Scripts;%PATH%\"",
    "    )",
    ")",
    "",
    "python --version > nul 2>&1",
    "if %ERRORLEVEL% NEQ 0 (",
    "    color 0C",
    "    echo.",
    "    echo   [ERROR] Python installation failed or PATH was not updated.",
    "    echo   Please restart this computer and run cmms_Start.bat again.",
    "    echo.",
    "    pause",
    "    exit /b 1",
    ")",
    "echo   [OK] Python installed and ready!",
    "echo.",
    "",
    ":python_ok",
    "echo   [OK] Python ready.",
    "echo.",
    "",
    "REM ── Install packages ─────────────────────────────────────────",
    "python -m pip install requests --quiet --disable-pip-version-check > nul 2>&1",
    "echo   [OK] Packages ready.",
    "echo.",
    "",
    "REM ── Download pusher script (use cached copy if server unreachable) ──",
    "REM    Download to a temp file so we never corrupt the cached copy mid-write.",
    "if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Downloading pusher script... >> \"%DIR%omtp_log.txt\"",
    "set PUSHER_TMP=%TEMP%\\cmms_pusher_tmp_%RANDOM%.py",
    `powershell -Command "try { Invoke-WebRequest -Uri '${pusherUrl}' -OutFile '%PUSHER_TMP%' -UseBasicParsing } catch { }" 2>nul`,
    "if exist \"%PUSHER_TMP%\" (",
    "    copy /y \"%PUSHER_TMP%\" \"%PUSHER%\" > nul 2>&1",
    "    del \"%PUSHER_TMP%\" > nul 2>&1",
    "    echo   [OK] Script updated.",
    "    if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Script updated from CMMS. >> \"%DIR%omtp_log.txt\"",
    ") else (",
    "    if exist \"%PUSHER%\" (",
    "        echo   [WARN] Server unreachable — using cached pusher script.",
    "        if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Server unreachable. Using cached script. >> \"%DIR%omtp_log.txt\"",
    "    ) else (",
    "        echo   [INFO] Server unreachable — extracting bundled script...",
    "        if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Server unreachable. Extracting bundled script. >> \"%DIR%omtp_log.txt\"",
    ...(b64Chunks.length > 0
      ? [
          // Write base64 chunks into a temp file (each echo line ≤ 6000 chars)
          "        set B64T=%TEMP%\\cmms_b64_%RANDOM%.tmp",
          "        (",
          ...b64Chunks.map(c => `            echo ${c}`),
          "        ) > \"%B64T%\"",
          // PowerShell: read temp file, strip newlines, decode, write Python file
          "        powershell -Command \"$b=[System.IO.File]::ReadAllText('%B64T%').Replace([char]13,'').Replace([char]10,''); [System.IO.File]::WriteAllBytes('%PUSHER%', [System.Convert]::FromBase64String($b))\" 2>nul",
          "        del \"%B64T%\" > nul 2>&1",
          "        if exist \"%PUSHER%\" (",
          "            echo   [OK] Bundled script extracted successfully.",
          "            if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Bundled script extracted. >> \"%DIR%omtp_log.txt\"",
          "        ) else (",
          "            echo.",
          "            echo   [ERROR] Failed to extract bundled script.",
          "            echo   Please re-download cmms_Start.bat from the CMMS and try again.",
          "            echo.",
          "            if not \"%~1\"==\"--silent\" pause",
          "            exit /b 1",
          "        )",
        ]
      : [
          "        echo.",
          "        echo   [ERROR] No bundled script found in this BAT file.",
          `        echo   Please re-download cmms_Start.bat from ${serverUrl} and try again.`,
          "        echo.",
          "        if not \"%~1\"==\"--silent\" pause",
          "        exit /b 1",
        ]),
    "    )",
    ")",
    "echo.",
    "",
    "REM ── Machine identity is managed automatically by the Python script ──",
    "",
    "if /i \"%~1\"==\"--silent\" echo [%date% %time%] BAT: Launching Python pusher... >> \"%DIR%omtp_log.txt\"",
    "goto :check_startup",
    "",
    "",
    "REM ── Offer Windows Startup ────────────────────────────────────",
    ":check_startup",
    "REM -- When launched by VBScript on startup, skip all prompts --",
    "if /i \"%~1\"==\"--silent\" goto :find_pythonw",
    "if exist \"%LNK%\" goto :already_installed",
    "echo ============================================================",
    "echo   AUTO-START ON WINDOWS STARTUP",
    "echo ============================================================",
    "echo.",
    "echo   Do you want this script to run AUTOMATICALLY every time",
    "echo   this computer starts — silently in the background?",
    "echo.",
    "echo   Y = Yes, add to startup (recommended for factory PCs)",
    "echo   N = No, I will start it manually",
    "echo.",
    "set /p INSTALL_STARTUP=  Your choice (Y/N): ",
    "if /i \"%INSTALL_STARTUP%\"==\"Y\" goto :do_install",
    "if /i \"%INSTALL_STARTUP%\"==\"y\" goto :do_install",
    "echo.",
    "echo   OK. Run this file manually each shift.",
    "echo.",
    "goto :find_pythonw",
    "",
    ":do_install",
    "REM ── Write VBScript launcher via PowerShell (Base64 → file) ───",
    `powershell -Command "[System.IO.File]::WriteAllText('%VBS%', [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('${vbsBase64}')))"`,
    "if not exist \"%VBS%\" (",
    "    echo   [ERROR] Could not create startup script.",
    "    goto :find_pythonw",
    ")",
    "REM ── Create a .lnk shortcut in the Startup folder pointing to the VBS ──",
    "REM    WorkingDirectory = BAT folder (without trailing \\) so 'cmms_Start.bat'",
    "REM    resolves correctly when Windows runs the shortcut at boot.",
    "powershell -Command \"$ws=New-Object -ComObject WScript.Shell; $s=$ws.CreateShortcut('%LNK%'); $s.TargetPath='%VBS%'; $s.WorkingDirectory='%DIR:~0,-1%'; $s.Description='Midea CMMS Log Pusher'; $s.Save()\"",
    "if not exist \"%LNK%\" (",
    "    echo   [ERROR] Could not create startup shortcut.",
    "    goto :find_pythonw",
    ")",
    "echo.",
    "echo   ============================================================",
    "echo   [OK] Added to Windows Startup!",
    "echo.",
    "echo   From now on, cmms_Start.bat will run COMPLETELY HIDDEN",
    "echo   every time this PC starts — no window, no interruption.",
    "echo.",
    "echo   Log file: %DIR%omtp_log.txt",
    "echo   To remove: delete cmms_Start.lnk from:",
    "echo   %STARTUP%",
    "echo   ============================================================",
    "echo.",
    "goto :find_pythonw",
    "",
    ":already_installed",
    "echo   [INFO] Already added to Windows Startup.",
    "echo.",
    "",
    "REM ── Find pythonw.exe (same folder as python.exe — always present with",
    "REM    the Windows installer). pythonw runs with NO console window.",
    ":find_pythonw",
    "set PYTHONW=",
    "for /f \"delims=\" %%P in ('where python 2^>nul') do (",
    "    if not defined PYTHONW (",
    "        set \"PYTHONW=%%~dpPpythonw.exe\"",
    "    )",
    ")",
    "if defined PYTHONW if not exist \"%PYTHONW%\" set PYTHONW=",
    "if not defined PYTHONW (",
    "    REM -- pythonw.exe not found alongside python — check common paths --",
    "    for %%V in (313 312 311 310 39 38) do (",
    "        if exist \"%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\pythonw.exe\" (",
    "            if not defined PYTHONW set \"PYTHONW=%LOCALAPPDATA%\\Programs\\Python\\Python%%V\\pythonw.exe\"",
    "        )",
    "    )",
    ")",
    "if not defined PYTHONW (",
    "    REM -- Last resort: use python (shows a console, but works) --",
    "    set PYTHONW=python",
    ")",
    "",
    "REM ── Launch the pusher completely hidden (no console window) ──",
    ":run",
    "REM -- In silent mode, just launch and exit; in interactive mode,",
    "REM -- show a brief message then close the window.",
    "if /i \"%~1\"==\"--silent\" goto :launch",
    "echo ============================================================",
    "echo   Starting OMTP Log Pusher in background...",
    "echo ============================================================",
    "echo.",
    `echo   Server : ${serverUrl}`,
    `echo   CSV    : ${pathTemplate}`,
    "echo   Log    : %DIR%omtp_log.txt",
    "echo.",
    "echo   The pusher is now running silently in the background.",
    "echo   Check omtp_log.txt to see activity.",
    "echo   This window will close in 5 seconds.",
    "echo.",
    "timeout /t 5 /nobreak > nul",
    "",
    ":launch",
    "start \"\" /high /b \"%PYTHONW%\" \"%PUSHER%\" ^",
    `  --api-url "${serverUrl}" ^`,
    `  --api-key "${apiKey}" ^`,
    `  --log-root "${logRoot}" ^`,
    "  --log-file \"%DIR%omtp_log.txt\" ^",
    "  --interval 30" + (columnMapArg ? " ^" : ""),
    ...(columnMapArg ? [columnMapArg] : []),
    "REM -- Brief pause so the window is visible before closing --",
    "if /i \"%~1\"==\"--silent\" timeout /t 2 /nobreak > nul",
    "exit /b 0",
    "",
  ].join(CRLF);

  res.setHeader("Content-Type", "application/octet-stream");
  res.setHeader("Content-Disposition", 'attachment; filename="cmms_Start.bat"');
  res.send(Buffer.from(bat, "utf-8"));
});

/* ── Legacy ── */
router.get("/omtp-setup", async (_req, res) => {
  const filePath = path.join(SCRIPTS_DIR, "OMTP_Setup.bat");
  if (!fs.existsSync(filePath)) return res.status(404).send("Not found");
  res.setHeader("Content-Type", "application/octet-stream");
  res.setHeader("Content-Disposition", 'attachment; filename="OMTP_Setup.bat"');
  res.send(fs.readFileSync(filePath, "utf-8"));
});

export default router;
