import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import downtimeRouter from "./downtime.js";
import inventoryRouter from "./inventory.js";
import sparepartOrdersRouter from "./sparepart-orders.js";
import preventiveMaintenanceRouter from "./preventive-maintenance.js";
import trainingRouter from "./training.js";
import productionRouter from "./production.js";
import tasksRouter from "./tasks.js";
import linePlansRouter from "./line-plans.js";
import attendanceRouter from "./attendance.js";
import brokenMachinesRouter from "./broken-machines.js";
import notificationsRouter from "./notifications.js";
import vacationRequestsRouter from "./vacation-requests.js";
import kpiRouter from "./kpi.js";
import shiftSettingsRouter from "./shift-settings.js";
import trainingExamsRouter from "./training-exams.js";
import announcementsRouter from "./announcements.js";
import machinesRouter from "./machines.js";
import auditLogsRouter from "./audit-logs.js";
import pushTokensRouter from "./push-tokens.js";
import siteSettingsRouter from "./site-settings.js";
import publicDowntimeRouter from "./public-downtime.js";
import workPhonesRouter from "./work-phones.js";
import defectsRouter from "./defects.js";
import factoryConfigRouter from "./factory-config.js";
import analyticsRouter from "./analytics.js";
import machineDataRouter from "./machine-data.js";
import downloadsRouter from "./downloads.js";
import changeoverTasksRouter from "./changeover-tasks.js";
import backupRouter from "./backup.js";
import diagnosticsRouter from "./diagnostics.js";
import aiAssistantRouter from "./ai-assistant.js";

const router = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/downtime", downtimeRouter);
router.use("/inventory", inventoryRouter);
router.use("/sparepart-orders", sparepartOrdersRouter);
router.use("/preventive-maintenance", preventiveMaintenanceRouter);
router.use("/training", trainingRouter);
router.use("/production", productionRouter);
router.use("/tasks", tasksRouter);
router.use("/line-plans", linePlansRouter);
router.use("/attendance", attendanceRouter);
router.use("/broken-machines", brokenMachinesRouter);
router.use("/notifications", notificationsRouter);
router.use("/vacation-requests", vacationRequestsRouter);
router.use("/kpi", kpiRouter);
router.use("/shift-settings", shiftSettingsRouter);
router.use("/training-exams", trainingExamsRouter);
router.use("/announcements", announcementsRouter);
router.use("/machines", machinesRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/push-tokens", pushTokensRouter);
router.use("/site-settings", siteSettingsRouter);
router.use("/public", publicDowntimeRouter);
router.use("/work-phones", workPhonesRouter);
router.use("/defects", defectsRouter);
router.use("/factory-config", factoryConfigRouter);
router.use("/analytics", analyticsRouter);
router.use("/machine-data", machineDataRouter);
router.use("/downloads", downloadsRouter);
router.use("/changeover-tasks", changeoverTasksRouter);
router.use("/backup", backupRouter);
router.use("/diagnostics", diagnosticsRouter);
router.use("/ai-assistant", aiAssistantRouter);

export default router;
